spring.application.name=inventory-management-system

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db
spring.datasource.username=inventory_user
spring.datasource.password=devpassword

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true